# This file is managed by macpro-mdct-core so if you'd like to change it let's do it there
name: Git Secrets

on:
  push:
  workflow_dispatch:

jobs:
  gitleaks-scan:
    name: gitleaks-scan # Keep as-is to avoid updating branch rules
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Run Gitleaks scan
        uses: docker://zricethezav/gitleaks
        with:
          args: detect --source /github/workspace/ --no-git --verbose
