# This file is managed by macpro-mdct-core so if you'd like to change it let's do it there
name: Update Code.json

on:
  schedule:
    # monthly on day 1
    - cron: "0 0 1 * *"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-code-json:
    name: Update code.json
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository (full history)
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: ".nvmrc"

      - name: Enable Corepack
        run: corepack enable

      - name: Setup Go
        uses: actions/setup-go@v6.0.0

      - name: Install SCC
        run: go install github.com/boyter/scc/v3@v3.5.0

      - name: Update code.json
        id: update-codejson
        uses: DSACMS/automated-codejson-generator@main
        with:
          BRANCH: "main"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get GitHub App token
        if: steps.update-codejson.outputs.method_used == 'pull_request'
        id: app-token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.GH_APP_ID }}
          private_key: ${{ secrets.GH_APP_PRIVATE_KEY }}

      - name: Auto-merge code.json PR
        if: steps.update-codejson.outputs.method_used == 'pull_request'
        run: |
          echo "PR URL: $PR_URL"

          # Approve and enable auto-merge
          gh pr review "$PR_URL" --approve
          gh pr merge "$PR_URL" --auto --squash
        env:
          PR_URL: ${{ steps.update-codejson.outputs.pr_url }}
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
